"""Generate the reference-architecture pages.

The blueprint catalogue is authored content, but it is *structured* authored
content: every page answers the same eight questions in the same order, so
engineers can compare patterns rather than read essays. Holding the content as
data and rendering it keeps that discipline enforceable — a new blueprint that
omits "when not to use" simply cannot be added.

    python3 tools/dev/make_blueprints.py
"""

from __future__ import annotations

import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
OUT = ROOT / "site/content/patterns"

B = {
    "simple-chat": dict(
        title="Simple Chat",
        summary="One prompt, one response. No retrieval, no tools.",
        use="Bounded question answering where the model's own knowledge is sufficient and the cost of being wrong is low.",
        avoid="Anything factual about the business. Without grounding you are betting on training data you do not control.",
        strengths=["Cheapest and fastest option", "Trivial to test and reason about",
                   "No infrastructure beyond the model gateway"],
        tradeoffs=["No grounding: hallucination risk on any factual question",
                   "No freshness: nothing updates without a prompt change",
                   "Ceiling on usefulness is reached quickly"],
        plugins=["none"],
        metrics=["pass_rate", "refusal_appropriateness"],
        diagram="flowchart LR\n    U[User] --> P[Prompt template]\n    P --> M[Model]\n    M --> O[Response]\n    M -.-> G{{Output guardrail}}\n    G --> O",
        failures=[("Confident invention of internal facts", "Move to `rag`. This is not a prompting problem."),
                  ("Prompt grows into a knowledge base", "The prompt is now an unversioned document store — move to retrieval.")],
    ),
    "rag": dict(
        title="Retrieval Augmented Generation",
        summary="Ground answers in a document corpus, with citations.",
        use="Answers must come from a specific corpus, the corpus changes independently of the model, and users need to check the source.",
        avoid="When the corpus is small enough to fit in context and stable — long context is simpler. When questions need computation over structured data — use `sql-agent`.",
        strengths=["Grounded and citable", "Corpus updates without touching the harness",
                   "Retrieval quality is measurable independently of generation"],
        tradeoffs=["Retrieval quality is the ceiling on answer quality",
                   "Chunking is fiddly and corpus-specific",
                   "Index freshness becomes an operational concern with an owner and an SLA",
                   "Permission-aware retrieval is significantly harder than it looks"],
        plugins=["retrieval index (vector or hybrid)", "document parser", "citation formatter (recommended)"],
        metrics=["grounding_rate", "citation_precision", "recall@k", "pass_rate"],
        diagram="flowchart LR\n    Q[Question] --> E[Embed]\n    E --> R[(Vector index)]\n    R --> C[Top-k context]\n    C --> G[Generate with citations]\n    G --> V{Grounding check}\n    V -->|ungrounded| G\n    V -->|grounded| A[Answer + citations]",
        failures=[("Right documents retrieved, wrong answer generated",
                   "Measure retrieval and generation separately before tuning either."),
                  ("Citations that do not support the claim",
                   "Add an exact-match grounding check — compose `citation-grounding`."),
                  ("Quality collapses on rare terms",
                   "Vectors miss exact tokens. Move to `hybrid-search`.")],
    ),
    "hybrid-search": dict(
        title="Hybrid Search",
        summary="Lexical and vector retrieval, fused and reranked.",
        use="Exact terms — clause numbers, error codes, product SKUs, people's names — matter as much as meaning.",
        avoid="When a plain vector index already meets the recall target. The second index is real operational cost.",
        strengths=["Catches what embeddings miss", "Much better on rare and out-of-vocabulary tokens",
                   "Fusion weights are tunable against a labelled set"],
        tradeoffs=["Two indexes to build, sync and monitor", "Fusion weights need their own evaluation",
                   "Reranking adds latency and cost per query"],
        plugins=["lexical index", "vector index", "reranker"],
        metrics=["recall@k", "mrr", "grounding_rate"],
        diagram="flowchart LR\n    Q[Query] --> L[Lexical search]\n    Q --> V[Vector search]\n    L --> F[Fusion]\n    V --> F\n    F --> RR[Reranker]\n    RR --> C[Context]",
        failures=[("Fusion tuned by intuition", "Tune against a labelled query set, and publish the set."),
                  ("Reranker doubles p95 latency", "Rerank only the top 20-30; measure before and after.")],
    ),
    "tool-calling": dict(
        title="Tool Calling",
        summary="The model reads or changes external state through a bounded tool set.",
        use="Real work requires touching another system, and the set of actions is known in advance.",
        avoid="When the action set is open-ended (that is `agentic`), or when the sequence is fixed (that is `workflow-automation` — cheaper and more predictable).",
        strengths=["Genuine capability rather than text about capability",
                   "Tool behaviour is deterministic and independently testable",
                   "Permissions are enforced by the tool, not by the prompt"],
        tradeoffs=["Tool schema quality dominates outcome quality",
                   "Error handling is most of the implementation",
                   "Every write tool is a blast radius; read-only by default is the sane posture"],
        plugins=["one plugin per tool", "audit sink"],
        metrics=["tool_selection_accuracy", "error_recovery_rate", "pass_rate"],
        diagram="flowchart LR\n    I[Input] --> M[Model]\n    M -->|tool call| T[Tool]\n    T -->|result| M\n    M --> O[Output]\n    T -.-> AU[(Audit)]",
        failures=[("Model calls the right tool with the wrong arguments",
                   "The schema is under-specified. Add examples and constrain enums."),
                  ("Silent failure on tool error",
                   "Feed the error back to the model explicitly and evaluate recovery as a metric."),
                  ("Write tools invoked speculatively",
                   "Separate read and write phases; require confirmation for writes.")],
    ),
    "workflow-automation": dict(
        title="Deterministic Workflow",
        summary="A fixed graph of model and tool steps; control flow lives in code.",
        use="The process is known, must be auditable, and must behave the same way twice.",
        avoid="When the path genuinely varies per input and enumerating branches is intractable.",
        strengths=["Deterministic control flow: reviewable, testable, predictable cost",
                   "Failures localise to a step", "Easiest pattern to gate and audit"],
        tradeoffs=["Inflexible to cases the author did not foresee",
                   "Longer to build than an agent loop", "Can accrete branches until it is unreadable"],
        plugins=["varies by step"],
        metrics=["step_success_rate", "pass_rate", "cost_per_case"],
        diagram="flowchart LR\n    S[Start] --> A[Step A: model]\n    A --> B[Step B: tool]\n    B --> C{Branch}\n    C -->|case 1| D[Step D]\n    C -->|case 2| E[Step E]\n    D --> F[End]\n    E --> F",
        failures=[("Branch explosion", "If the graph exceeds ~15 steps, reconsider the decomposition."),
                  ("Model output used as control flow", "That makes it an agent with extra steps — be explicit about which you are building.")],
    ),
    "document-review": dict(
        title="Document Review",
        summary="Long documents assessed against a rubric or playbook, clause by clause.",
        use="A long document must be checked against a known standard, and the reviewer needs to verify each finding.",
        avoid="When the document is short enough to review whole, or when there is no written standard to check against — build the standard first.",
        strengths=["Unit-level precision with verifiable citations",
                   "Coverage reporting: what was checked, and what was not",
                   "Findings map onto how experts already work"],
        tradeoffs=["Segmentation quality gates everything downstream",
                   "Long documents are slow and costly",
                   "Requires a written standard, which is often the real project"],
        plugins=["parser with anchors", "playbook or rubric index", "segmentation harness"],
        metrics=["coverage", "grounding_rate", "expert_agreement", "severity_agreement"],
        diagram="flowchart LR\n    D[Document] --> P[Parse + anchors]\n    P --> S[Segment]\n    S --> C[Classify unit]\n    C --> R[Retrieve standard]\n    R --> A[Assess]\n    A --> G{Grounded?}\n    G -->|no| A\n    G -->|yes| F[Findings + coverage]\n    F --> H[Human sign-off]",
        failures=[("Findings the reviewer cannot verify", "Carry anchors end to end; cite page and paragraph."),
                  ("Silent gaps where the standard has no position", "Emit UNMATCHED rather than forcing a nearest match — the gaps are valuable output."),
                  ("Split obligations assessed in isolation", "Segment on document structure, not token count.")],
    ),
    "planner": dict(
        title="Planner / Executor",
        summary="Produce a plan, validate it, then execute it separately.",
        use="Multi-step tasks where the plan is worth inspecting — or approving — before anything happens.",
        avoid="Short tasks where planning costs more than doing.",
        strengths=["The plan is reviewable, cacheable and reusable",
                   "Execution failures localise to a step",
                   "Human approval fits naturally between the phases"],
        tradeoffs=["Two model passes: more cost and latency",
                   "Plans drift from execution reality", "Replanning logic is easy to get wrong"],
        plugins=["varies", "plan validator"],
        metrics=["plan_validity", "replan_rate", "pass_rate"],
        diagram="flowchart LR\n    G[Goal] --> P[Plan]\n    P --> V{Valid?}\n    V -->|no| P\n    V -->|yes| A[Approve optional]\n    A --> E[Execute steps]\n    E --> M{Deviation?}\n    M -->|yes| P\n    M -->|no| R[Result]",
        failures=[("Plans that ignore execution constraints", "Validate against the real tool set, not a description of it.")],
    ),
    "multi-agent": dict(
        title="Multi-agent",
        summary="Several cooperating roles with an explicit coordination protocol.",
        use="Roles genuinely need different tools, contexts or trust boundaries — for example a drafter that cannot see production data and a reviewer that can.",
        avoid="Almost always. **Try a deterministic workflow with one model first.**",
        strengths=["Real specialisation of tools and context",
                   "Parallelism across independent roles",
                   "Trust boundaries can be enforced per role"],
        tradeoffs=["3-10x the cost of a single-model equivalent",
                   "Hard to debug: failures emerge from interactions, not steps",
                   "Non-deterministic; evaluation needs many more runs to be meaningful",
                   "Coordination overhead frequently exceeds the specialisation benefit"],
        plugins=["orchestration", "per-role tools", "shared memory or message log"],
        metrics=["per_role_success", "coordination_overhead", "cost_per_case", "pass_rate"],
        diagram="flowchart TB\n    C[Coordinator] --> A[Agent: research]\n    C --> B[Agent: draft]\n    C --> D[Agent: review]\n    A --> S[(Shared context)]\n    B --> S\n    D --> S\n    S --> C\n    C --> O[Output]",
        anti_pattern=(
            "Before choosing multi-agent, try `workflow-automation` with a single model. In our estate, "
            "6 of the 9 multi-agent harnesses reviewed in 2026-H1 were reimplemented as deterministic "
            "workflows with equal or better quality at 25-40% of the cost. Multi-agent earns its cost when "
            "roles need genuinely different tools, contexts or trust boundaries — not when the task merely "
            "has several steps."),
        failures=[("Agents talking in circles", "Hard iteration ceiling, then fail loudly."),
                  ("Cost 10x the estimate", "Budget per run, enforced by the runtime, not by hope.")],
    ),
    "research-assistant": dict(
        title="Research Assistant",
        summary="Open-ended investigation across many sources, producing a sourced brief.",
        use="The question is genuinely open and breadth matters more than a single precise answer.",
        avoid="When the answer lives in one known corpus — that is `rag`, at a tenth of the cost.",
        strengths=["Surfaces unknowns and contradictions",
                   "A rejected-sources list makes the output reviewable",
                   "High perceived value for expensive human time"],
        tradeoffs=["Unbounded cost without hard ceilings",
                   "Quality is genuinely hard to evaluate",
                   "Breadth encourages plausible-sounding synthesis over evidence"],
        plugins=["search across corpora", "retrieval", "citation formatter"],
        metrics=["source_diversity", "claim_support_rate", "cost_per_report", "human_agreement"],
        diagram="flowchart LR\n    T[Topic] --> P[Plan sweep]\n    P --> S1[Corpus A]\n    P --> S2[Corpus B]\n    P --> S3[Corpus C]\n    S1 & S2 & S3 --> D[Dedupe + rank]\n    D --> W[Write brief]\n    W --> G{Every claim sourced?}\n    G -->|no| D\n    G -->|yes| B[Brief + sources]",
        failures=[("Cost varies by an order of magnitude", "Set a depth parameter that maps to a hard ceiling."),
                  ("Same document cited twice under different ids", "Deduplicate across corpora before writing.")],
    ),
    "code-assistant": dict(
        title="Code Assistant",
        summary="Generating or reviewing code, with compilers and tests as the oracle.",
        use="Software engineering tasks where correctness can be checked mechanically.",
        avoid="Codebases without tests — you lose the one advantage this pattern has.",
        strengths=["Verifiable: tests and compilers are a real oracle, which almost no other pattern has",
                   "Failures are cheap to detect", "Feedback loops can be automated end to end"],
        tradeoffs=["Repository context selection is the hard problem",
                   "Generated code needs the same security review as written code",
                   "Sandbox execution is required, and is real infrastructure"],
        plugins=["repository context", "test runner (sandboxed)", "linters"],
        metrics=["test_pass_rate", "build_rate", "review_acceptance", "finding_precision"],
        diagram="flowchart LR\n    T[Task or diff] --> C[Gather repo context]\n    C --> M[Model]\n    M --> P[Proposal]\n    P --> X[Run tests in sandbox]\n    X -->|fail| M\n    X -->|pass| R[Result]",
        failures=[("Confident findings that do not reproduce", "Require reproduction before emitting a defect claim."),
                  ("Context window filled with irrelevant files", "Rank context by dependency distance, not by name similarity.")],
    ),
    "sql-agent": dict(
        title="SQL Agent",
        summary="Natural language over structured data, executed read-only.",
        use="Analysts and business users need answers from a modelled warehouse, and results can be checked.",
        avoid="Unmodelled schemas. Without a semantic layer the model re-infers column meaning per question and gets it subtly wrong.",
        strengths=["High perceived value", "Results are checkable by running the query",
                   "The generated SQL is an artefact people can review and reuse"],
        tradeoffs=["Schema comprehension is the whole problem",
                   "**Write access must be prohibited**, not merely discouraged",
                   "Wrong-but-plausible answers are expensive and hard to notice",
                   "Row-level security must be the caller's, not the harness's"],
        plugins=["read-only database connector", "schema or semantic layer catalogue"],
        metrics=["execution_accuracy", "result_exact_match", "interpretation_agreement"],
        diagram="flowchart LR\n    Q[Question] --> S[Semantic layer lookup]\n    S --> G[Generate SQL]\n    G --> V{Parse + permission + cost check}\n    V -->|reject| G\n    V -->|accept| E[(Read-only execute)]\n    E --> X[Explain interpretation]\n    X --> R[Result]",
        failures=[("Right query, wrong question", "Publish the interpretation alongside the result; most errors are here."),
                  ("Fiscal versus calendar periods", "Encode period definitions in the semantic layer, never in the prompt."),
                  ("Runaway query cost", "Cost-estimate before execution and cap it.")],
    ),
    "knowledge-assistant": dict(
        title="Knowledge Assistant",
        summary="One front door for enterprise-wide question answering.",
        use="Users do not know which system holds the answer, and permission-aware retrieval across sources is available.",
        avoid="Before permission-aware retrieval exists. A knowledge assistant that leaks is worse than no assistant.",
        strengths=["One entry point instead of ten", "High adoption; often the flagship internal use case",
                   "Consolidates retrieval investment"],
        tradeoffs=["Permission-aware retrieval is the hard part and is non-negotiable",
                   "Ownership is diffuse: everyone's corpus, nobody's problem",
                   "Quality varies wildly by corpus, and users experience the worst case"],
        plugins=["permission-aware retrieval", "identity context", "citation formatter"],
        metrics=["grounding_rate", "permission_leak_rate (must be 0)", "coverage", "deflection_rate"],
        diagram="flowchart LR\n    U[User + identity] --> R[Permission-aware retrieval]\n    R --> C[Context from allowed sources]\n    C --> G[Generate with citations]\n    G --> A[Answer]\n    R -.->|denied sources logged| AU[(Audit)]",
        failures=[("A single unindexed corpus destroys trust", "Publish coverage: say what is not searched."),
                  ("Permission bypass through cached context", "Scope caches by identity, and test for it explicitly.")],
    ),
    "evaluation-harness": dict(
        title="Evaluation Harness",
        summary="A harness whose product is a judgement about another system.",
        use="Judging outputs at a scale humans cannot reach, with human review to calibrate.",
        avoid="As a replacement for human review rather than an amplifier of it.",
        strengths=["Reusable across the estate", "Makes every other harness's evidence cheaper to produce",
                   "Judgements are themselves measurable against human labels"],
        tradeoffs=["Judge drift: the judge model changes and the scores move for no other reason",
                   "Calibration is ongoing work, not a one-off",
                   "Rubric quality is the ceiling; a vague rubric produces confident noise"],
        plugins=["judge model access", "dataset store", "metric library"],
        metrics=["human_agreement", "calibration_stability", "inter_judge_agreement"],
        diagram="flowchart LR\n    O[Outputs under test] --> R[Rubric vN]\n    R --> J[Judge model pinned]\n    J --> S[Scores]\n    S --> C{Calibration set agreement}\n    C -->|below gate| H[Human recalibration]\n    C -->|ok| P[Publish]",
        failures=[("Scores move after a model upgrade", "Pin the judge build, record it in every report, re-baseline deliberately."),
                  ("Judge agrees with itself, not with experts", "Maintain a calibration set with a hard agreement gate.")],
    ),
}


def render(pid: str, b: dict) -> str:
    fm = [
        "---",
        f"title: {b['title']}",
        # The slug is the taxonomy term id: URLs must match `spec.architecture.pattern`,
        # not a slugified human title ("Planner / Executor" -> "planner-").
        f"slug: {pid}",
        f"summary: {b['summary']}",
        "mermaid: true",
        "---",
        "",
        f"{b['summary']}",
        "",
        "## Diagram",
        "",
        "```mermaid",
        b["diagram"],
        "```",
        "",
        "## When to use",
        "",
        b["use"],
        "",
        "## When *not* to use",
        "",
        b["avoid"],
        "",
        "## Strengths",
        "",
        *[f"- {s}" for s in b["strengths"]],
        "",
        "## Trade-offs",
        "",
        *[f"- {t}" for t in b["tradeoffs"]],
        "",
    ]
    if b.get("anti_pattern"):
        fm += ["## Before you choose this", "", f"> {b['anti_pattern']}", ""]
    fm += [
        "## Required plugin classes",
        "",
        *[f"- {p}" for p in b["plugins"]],
        "",
        "## Metrics that matter",
        "",
        "| Metric | Why it matters for this pattern |",
        "|---|---|",
        *[f"| `{m}` | |" for m in b["metrics"]],
        "",
        "## Common failure modes",
        "",
        "| Failure | Mitigation |",
        "|---|---|",
        *[f"| {f} | {m} |" for f, m in b["failures"]],
        "",
        "## Scaffold one",
        "",
        "```shell",
        f"harnessctl new my-harness --pattern {pid}",
        "```",
        "",
        "Generates the standard repository layout, a working prompt, a starter evaluation",
        "suite for this pattern's metrics, and a pipeline that is green on the first run.",
        "",
        "## Harnesses implementing this pattern",
        "",
    ]
    return "\n".join(fm)


def main() -> int:
    for pid, b in B.items():
        d = OUT / pid
        d.mkdir(parents=True, exist_ok=True)
        (d / "_index.md").write_text(render(pid, b))
    print(f"{len(B)} blueprint page(s) written to {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
